/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControllerCita;
import controlador.ControllerCitaDueno;
import controlador.ControllerCitasFecha;
import controlador.ControllerDueno;
import controlador.ControllerMascota;
import controlador.ControllerUsuario;
import controlador.ControllerVeterinario;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Daniel
 */
public class frmVentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmVentanaPrincipal
     *
     *
     */
    public void permisos(String tipoUsuario) {

        if ("Asistente".endsWith(tipoUsuario)) {
            btnUsuarios.setVisible(false);
            btnVeterinarios.setVisible(false);

        }
        if ("Administrador".endsWith(tipoUsuario)) {
            btnRegistroCitas.setVisible(false);

        }
    }

    public frmVentanaPrincipal(String idUsuario, String nombreUsuario, String tipoUsuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        setTitle("Sistema de Mi Mascota S.A");
        lblIdUsuario.setText(idUsuario);
        lblNombreUsuario.setText(nombreUsuario);
        lblTipodeUsuario.setText(tipoUsuario);
        permisos(tipoUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblIdUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblTipodeUsuario = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        menuCatalogoDatos = new javax.swing.JMenu();
        btnUsuarios = new javax.swing.JMenuItem();
        btnVeterinarios = new javax.swing.JMenuItem();
        btnMascota = new javax.swing.JMenuItem();
        btnDueño = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        btnRegistroCitas = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        btnCitasporFecha = new javax.swing.JMenuItem();
        btnCitasporDueño = new javax.swing.JMenuItem();
        menuAcercade = new javax.swing.JMenu();
        Manual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        desktopPane.setPreferredSize(new java.awt.Dimension(891, 587));

        lblIdUsuario.setText("ID");

        lblNombreUsuario.setText("Nombre Usuario");

        lblTipodeUsuario.setText("Tipo de Usuario ");

        desktopPane.setLayer(lblIdUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(lblNombreUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(lblTipodeUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipodeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblIdUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblTipodeUsuario)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        menuArchivo.setText("Archivo");
        menuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(btnSalir);

        menuBar.add(menuArchivo);

        menuCatalogoDatos.setText("Catalogo de Datos");

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        menuCatalogoDatos.add(btnUsuarios);

        btnVeterinarios.setText("Veterinarios");
        btnVeterinarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeterinariosActionPerformed(evt);
            }
        });
        menuCatalogoDatos.add(btnVeterinarios);

        btnMascota.setText("Mascota");
        btnMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMascotaActionPerformed(evt);
            }
        });
        menuCatalogoDatos.add(btnMascota);

        btnDueño.setText("Dueño");
        btnDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDueñoActionPerformed(evt);
            }
        });
        menuCatalogoDatos.add(btnDueño);

        menuBar.add(menuCatalogoDatos);

        menuProcesos.setText("Procesos");
        menuProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesosActionPerformed(evt);
            }
        });

        btnRegistroCitas.setText("Registro de Citas");
        btnRegistroCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroCitasActionPerformed(evt);
            }
        });
        menuProcesos.add(btnRegistroCitas);

        menuBar.add(menuProcesos);

        menuReportes.setText("Reportes");

        btnCitasporFecha.setText("Citas por fecha");
        btnCitasporFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasporFechaActionPerformed(evt);
            }
        });
        menuReportes.add(btnCitasporFecha);

        btnCitasporDueño.setText("Citas por Dueño");
        btnCitasporDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasporDueñoActionPerformed(evt);
            }
        });
        menuReportes.add(btnCitasporDueño);

        menuBar.add(menuReportes);

        menuAcercade.setText("Acerca de ");
        menuAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercadeActionPerformed(evt);
            }
        });

        Manual.setText("Manual de Usuario");
        Manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualActionPerformed(evt);
            }
        });
        menuAcercade.add(Manual);

        menuBar.add(menuAcercade);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        frmCatalogoUsuario frm = new frmCatalogoUsuario();

        ControllerUsuario con = new ControllerUsuario(frm);
        desktopPane.add(frm);
        con.iniciar();
        frm.toFront();
        frm.setLocation(desktopPane.getWidth() / 2 - frm.getWidth() / 2, desktopPane.getHeight() / 2 - frm.getHeight() / 2);
        frm.setVisible(true);

    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnVeterinariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeterinariosActionPerformed
        frmCatalogoVeterinario frm = new frmCatalogoVeterinario();

        ControllerVeterinario con = new ControllerVeterinario(frm);
        desktopPane.add(frm);
        con.iniciar();
        frm.toFront();
        frm.setLocation(desktopPane.getWidth() / 2 - frm.getWidth() / 2, desktopPane.getHeight() / 2 - frm.getHeight() / 2);
        frm.setVisible(true);


    }//GEN-LAST:event_btnVeterinariosActionPerformed

    private void btnMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMascotaActionPerformed
        frmCatalogoMascota frm = new frmCatalogoMascota();

        ControllerMascota con = new ControllerMascota(frm);
        desktopPane.add(frm);
        con.iniciar();
        frm.toFront();
        frm.setLocation(desktopPane.getWidth() / 2 - frm.getWidth() / 2, desktopPane.getHeight() / 2 - frm.getHeight() / 2);
        frm.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnMascotaActionPerformed

    private void btnRegistroCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroCitasActionPerformed
        // TODO add your handling code here:
        frmCatalogoCita obj = new frmCatalogoCita();
        desktopPane.add(obj);
        ControllerCita con = new ControllerCita(obj);
        con.iniciar();
        obj.toFront();
        obj.setLocation(desktopPane.getWidth() / 2 - obj.getWidth() / 2, desktopPane.getHeight() / 2 - obj.getHeight() / 2);
        obj.setVisible(true);
    }//GEN-LAST:event_btnRegistroCitasActionPerformed

    private void menuProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProcesosActionPerformed

    private void btnDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDueñoActionPerformed

        frmCatalogoDueno obj = new frmCatalogoDueno();
        desktopPane.add(obj);
        ControllerDueno con = new ControllerDueno(obj);
        con.iniciar();
        obj.toFront();
        obj.setLocation(desktopPane.getWidth() / 2 - obj.getWidth() / 2, desktopPane.getHeight() / 2 - obj.getHeight() / 2);
        obj.setVisible(true);
    }//GEN-LAST:event_btnDueñoActionPerformed

    private void btnCitasporFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasporFechaActionPerformed
        frmCitasporFecha obj = new frmCitasporFecha();
        desktopPane.add(obj);
        ControllerCitasFecha con = new ControllerCitasFecha(obj);
        con.iniciar();
        obj.toFront();
        obj.setLocation(desktopPane.getWidth() / 2 - obj.getWidth() / 2, desktopPane.getHeight() / 2 - obj.getHeight() / 2);
        obj.setVisible(true);

    }//GEN-LAST:event_btnCitasporFechaActionPerformed

    private void btnCitasporDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasporDueñoActionPerformed
        frmCitasporDueno obj = new frmCitasporDueno();
        desktopPane.add(obj);
        ControllerCitaDueno con = new ControllerCitaDueno(obj);
        con.iniciar();
        obj.toFront();
        obj.setLocation(desktopPane.getWidth() / 2 - obj.getWidth() / 2, desktopPane.getHeight() / 2 - obj.getHeight() / 2);
        obj.setVisible(true);

    }//GEN-LAST:event_btnCitasporDueñoActionPerformed

    private void menuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuArchivoActionPerformed

    private void menuAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercadeActionPerformed


    }//GEN-LAST:event_menuAcercadeActionPerformed

    private void ManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualActionPerformed
        try {
            File path = new File("PDF/Manual de Usuario.pdf");
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            ex.printStackTrace();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_ManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentanaPrincipal(lblIdUsuario.getText(), lblNombreUsuario.getText(), lblTipodeUsuario.getText()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Manual;
    private javax.swing.JMenuItem btnCitasporDueño;
    private javax.swing.JMenuItem btnCitasporFecha;
    private javax.swing.JMenuItem btnDueño;
    private javax.swing.JMenuItem btnMascota;
    private javax.swing.JMenuItem btnRegistroCitas;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnUsuarios;
    private javax.swing.JMenuItem btnVeterinarios;
    public javax.swing.JDesktopPane desktopPane;
    public static javax.swing.JLabel lblIdUsuario;
    public static javax.swing.JLabel lblNombreUsuario;
    public static javax.swing.JLabel lblTipodeUsuario;
    private javax.swing.JMenu menuAcercade;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCatalogoDatos;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
